# Generated by Django 3.0.2 on 2020-01-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApiApp', '0002_auto_20200108_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='age',
            field=models.CharField(max_length=10),
        ),
    ]
